import { UserProfile, LeaveRequest, ParentConsent, DigitalPass, GateLog, AuditLog, NotificationItem } from '../types';

export const DEMO_USERS: Record<string, UserProfile> = {
  student: {
    id: 'usr-student-101',
    email: 'soundhar@bitsathy',
    name: 'SOUNDHAR RAJ V',
    role: 'STUDENT',
    studentType: 'HOSTELLER',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98765 43210',
    department: 'Agriculture Engineering',
    registerNumber: '7376232AG147',
    hostelBlock: 'Emerald Block - A',
    roomNumber: '304',
    yearOfStudy: 3,
    parentName: 'V. Raj',
    parentPhone: '+91 98123 45678',
    parentEmail: 'parent@bitsathy',
    advisorName: 'Dr. K. Arunkumar',
    wardenName: 'Prof. M. Ramesh',
    hodName: 'Dr. S. Priya'
  },
  bharathees: {
    id: 'usr-student-102',
    email: 'bharathees@bitsathy',
    name: 'BHARATHEES K',
    role: 'STUDENT',
    studentType: 'DAY_SCHOLAR',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98765 43211',
    department: 'Agriculture Engineering',
    registerNumber: '7376232AG106',
    hostelBlock: 'Day Scholar',
    roomNumber: '',
    yearOfStudy: 2,
    parentName: 'B. Kumar',
    parentPhone: '+91 98123 45679',
    parentEmail: 'parent2@bitsathy',
    advisorName: 'Dr. K. Arunkumar',
    wardenName: 'Prof. M. Ramesh'
  },
  vishnu: {
    id: 'usr-student-103',
    email: 'vishnu@bitsathy',
    name: 'VISHNU SELVAN',
    role: 'STUDENT',
    studentType: 'HOSTELLER',
    avatarUrl: 'https://images.unsplash.com/photo-1545996124-1d3f5eec0f3b?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98765 43212',
    department: 'Agriculture Engineering',
    registerNumber: '7376232AG152',
    hostelBlock: 'Emerald Block - B',
    roomNumber: '210',
    yearOfStudy: 3,
    parentName: 'S. Selvan',
    parentPhone: '+91 98123 45670',
    parentEmail: 'parent3@bitsathy',
    advisorName: 'Dr. K. Arunkumar',
    wardenName: 'Prof. M. Ramesh',
    hodName: 'Dr. S. Priya'
  },
  parent: {
    id: 'usr-parent-201',
    email: 'parent@bitsathy',
    name: 'Parent User',
    role: 'PARENT',
    phone: '+91 98123 45678',
    parentPhone: '+91 98123 45678',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80'
  },
  mentor: {
    id: 'usr-mentor-501',
    email: 'mentor@bitsathy',
    name: 'Mentor / Advisor',
    role: 'ADVISOR',
    department: 'Computer Science & Engineering',
    phone: '+91 94421 55443',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80'
  },
  warden: {
    id: 'usr-warden-401',
    email: 'warden@bitsathy',
    name: 'Warden',
    role: 'WARDEN',
    department: 'Hostel Administration',
    hostelBlock: 'Emerald Block - A',
    phone: '+91 94433 88776',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80'
  },
  security: {
    id: 'usr-security-601',
    email: 'security@bitsathy',
    name: 'Security',
    role: 'SECURITY',
    department: 'Campus Security - Gate 1',
    phone: '+91 98422 11000',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80'
  },
  management: {
    id: 'usr-management-801',
    email: 'management@bitsathy',
    name: 'Management',
    role: 'MANAGEMENT',
    department: 'Campus Administration',
    phone: '+91 422 2655500',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80'
  },
  admin: {
    id: 'usr-admin-701',
    email: 'admin@bitsathy',
    name: 'Admin',
    role: 'ADMIN',
    department: 'Academic Affairs & Campus Management',
    phone: '+91 422 2655500',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80'
  }
};

const now = new Date();
const todayStr = now.toISOString().split('T')[0];

export const MOCK_REQUESTS: LeaveRequest[] = [
  {
    id: 'req-210',
    requestNumber: 'OUT-2026-0910',
    studentId: 'usr-student-102',
    studentName: 'BHARATHEES K',
    registerNumber: '7376232AG106',
    department: 'Agriculture Engineering',
    hostelBlock: 'Day Scholar',
    roomNumber: 'N/A',
    type: 'OD',
    leaveTitle: 'OnDuty - Project Presentation',
    durationDays: '2 days',
    reason: 'State Level Project Expo & Presentation',
    destination: 'Coimbatore Institute of Technology',
    emergencyContact: '+91 98123 45679',
    startDate: '2026-08-14T09:00',
    endDate: '2026-08-15T18:00',
    status: 'APPROVAL_PENDING',
    currentStage: 'Parent Approved • Pending Mentor Approval',
    parentConsentId: 'cns-210',
    parentStatus: 'APPROVED',
    advisorStatus: 'PENDING',
    wardenStatus: 'NOT_APPLICABLE' as any,
    hodStatus: 'PENDING',
    isException: false,
    createdAt: new Date('2026-08-12T10:00:00').toISOString(),
    updatedAt: new Date('2026-08-12T10:00:00').toISOString()
  },
  {
    id: 'req-201',
    requestNumber: 'OUT-2026-0901',
    studentId: 'usr-student-101',
    studentName: 'SOUNDHAR RAJ V',
    registerNumber: '7376232AG147',
    department: 'Agriculture Engineering',
    hostelBlock: 'Emerald Block - A',
    roomNumber: '304',
    type: 'OD',
    leaveTitle: 'OnDuty - Internship',
    durationDays: '16 days',
    reason: 'Internship - Full Stack Developer',
    destination: 'Bangalore Tech Park',
    emergencyContact: '+91 98123 45678',
    startDate: '2026-08-12T09:00',
    endDate: '2026-08-27T18:00',
    status: 'APPROVAL_PENDING',
    currentStage: 'Parent Approved • Pending Warden Sign-off',
    parentConsentId: 'cns-201',
    parentStatus: 'APPROVED',
    advisorStatus: 'NOT_APPLICABLE' as any,
    wardenStatus: 'PENDING',
    hodStatus: 'PENDING',
    isException: false,
    createdAt: new Date('2026-08-11T10:00:00').toISOString(),
    updatedAt: new Date('2026-08-11T10:00:00').toISOString()
  },
  {
    id: 'req-202',
    requestNumber: 'OUT-2026-0902',
    studentId: 'usr-student-101',
    studentName: 'SOUNDHAR RAJ V',
    registerNumber: '7376232AG147',
    department: 'Agriculture Engineering',
    hostelBlock: 'Emerald Block - A',
    roomNumber: '304',
    type: 'OD',
    leaveTitle: 'OnDuty - Internship',
    durationDays: '15 days',
    reason: 'Internship - Full Stack Developer',
    destination: 'Chennai Tech Park',
    emergencyContact: '+91 98123 45678',
    startDate: '2026-07-28T09:00',
    endDate: '2026-08-11T18:00',
    status: 'APPROVED',
    currentStage: 'Pass Generated - Active Gate Exit',
    parentConsentId: 'cns-202',
    parentStatus: 'APPROVED',
    advisorStatus: 'APPROVED',
    wardenStatus: 'APPROVED',
    hodStatus: 'APPROVED',
    isException: false,
    createdAt: new Date('2026-07-25T10:00:00').toISOString(),
    updatedAt: new Date('2026-07-25T10:00:00').toISOString()
  },
  {
    id: 'req-203',
    requestNumber: 'OUT-2026-0903',
    studentId: 'usr-student-101',
    studentName: 'SOUNDHAR RAJ V',
    registerNumber: '7376232AG147',
    department: 'Agriculture Engineering',
    hostelBlock: 'Emerald Block - A',
    roomNumber: '304',
    type: 'OD',
    leaveTitle: 'OnDuty - Internship',
    durationDays: '15 days',
    reason: 'Internship - Full Stack Developer',
    destination: 'Coimbatore Innovation Hub',
    emergencyContact: '+91 98123 45678',
    startDate: '2026-07-13T09:00',
    endDate: '2026-07-27T18:00',
    status: 'APPROVED',
    currentStage: 'Completed - Pass Verified at Gate',
    parentConsentId: 'cns-203',
    parentStatus: 'APPROVED',
    advisorStatus: 'APPROVED',
    wardenStatus: 'APPROVED',
    hodStatus: 'APPROVED',
    isException: false,
    createdAt: new Date('2026-07-10T10:00:00').toISOString(),
    updatedAt: new Date('2026-07-10T10:00:00').toISOString()
  },
  {
    id: 'req-204',
    requestNumber: 'OUT-2026-0904',
    studentId: 'usr-student-101',
    studentName: 'SOUNDHAR RAJ V',
    registerNumber: '7376232AG147',
    department: 'Agriculture Engineering',
    hostelBlock: 'Emerald Block - A',
    roomNumber: '304',
    type: 'OD',
    leaveTitle: 'OnDuty - Internship',
    durationDays: '62 days',
    reason: 'Full Stack Development Intern',
    destination: 'Hyderabad R&D Center',
    emergencyContact: '+91 98123 45678',
    startDate: '2026-07-13T09:00',
    endDate: '2026-09-12T18:00',
    status: 'REJECTED',
    currentStage: 'Exceeds maximum single term internship OD duration',
    parentStatus: 'PENDING',
    advisorStatus: 'REJECTED',
    wardenStatus: 'REJECTED',
    hodStatus: 'REJECTED',
    isException: false,
    createdAt: new Date('2026-07-08T10:00:00').toISOString(),
    updatedAt: new Date('2026-07-08T10:00:00').toISOString()
  },
  {
    id: 'req-205',
    requestNumber: 'OUT-2026-0905',
    studentId: 'usr-student-101',
    studentName: 'SOUNDHAR RAJ V',
    registerNumber: '7376232AG147',
    department: 'Agriculture Engineering',
    hostelBlock: 'Emerald Block - A',
    roomNumber: '304',
    type: 'LEAVE',
    leaveTitle: 'Leave',
    durationDays: '1 day',
    reason: 'GP',
    destination: 'Home',
    emergencyContact: '+91 98123 45678',
    startDate: '2026-06-29T09:00',
    endDate: '2026-06-29T20:00',
    status: 'APPROVED',
    currentStage: 'Completed',
    parentConsentId: 'cns-205',
    parentStatus: 'APPROVED',
    advisorStatus: 'APPROVED',
    wardenStatus: 'APPROVED',
    hodStatus: 'APPROVED',
    isException: false,
    createdAt: new Date('2026-06-28T10:00:00').toISOString(),
    updatedAt: new Date('2026-06-28T10:00:00').toISOString()
  },
  {
    id: 'req-206',
    requestNumber: 'OUT-2026-0906',
    studentId: 'usr-student-101',
    studentName: 'SOUNDHAR RAJ V',
    registerNumber: '7376232AG147',
    department: 'Agriculture Engineering',
    hostelBlock: 'Emerald Block - A',
    roomNumber: '304',
    type: 'LEAVE',
    leaveTitle: 'Leave',
    durationDays: '2 days',
    reason: 'Sick leave',
    destination: 'Home - Erode',
    emergencyContact: '+91 98123 45678',
    startDate: '2026-06-24T09:00',
    endDate: '2026-06-25T18:00',
    status: 'APPROVED',
    currentStage: 'Completed',
    parentConsentId: 'cns-206',
    parentStatus: 'APPROVED',
    advisorStatus: 'APPROVED',
    wardenStatus: 'APPROVED',
    hodStatus: 'APPROVED',
    isException: false,
    createdAt: new Date('2026-06-23T10:00:00').toISOString(),
    updatedAt: new Date('2026-06-23T10:00:00').toISOString()
  },
  {
    id: 'req-207',
    requestNumber: 'OUT-2026-0907',
    studentId: 'usr-student-101',
    studentName: 'SOUNDHAR RAJ V',
    registerNumber: '7376232AG147',
    department: 'Agriculture Engineering',
    hostelBlock: 'Emerald Block - A',
    roomNumber: '304',
    type: 'LEAVE',
    leaveTitle: 'Leave',
    durationDays: '1 day',
    reason: 'sick leave',
    destination: 'Home',
    emergencyContact: '+91 98123 45678',
    startDate: '2026-06-20T09:00',
    endDate: '2026-06-20T20:00',
    status: 'APPROVED',
    currentStage: 'Completed',
    parentConsentId: 'cns-207',
    parentStatus: 'APPROVED',
    advisorStatus: 'APPROVED',
    wardenStatus: 'APPROVED',
    hodStatus: 'APPROVED',
    isException: false,
    createdAt: new Date('2026-06-19T10:00:00').toISOString(),
    updatedAt: new Date('2026-06-19T10:00:00').toISOString()
  },
  {
    id: 'req-208',
    requestNumber: 'OUT-2026-0908',
    studentId: 'usr-student-101',
    studentName: 'SOUNDHAR RAJ V',
    registerNumber: '7376232AG147',
    department: 'Agriculture Engineering',
    hostelBlock: 'Emerald Block - A',
    roomNumber: '304',
    type: 'LEAVE',
    leaveTitle: 'Leave',
    durationDays: '1 day',
    reason: 'Land dispute',
    destination: 'Home Town',
    emergencyContact: '+91 98123 45678',
    startDate: '2026-06-16T09:00',
    endDate: '2026-06-16T20:00',
    status: 'APPROVED',
    currentStage: 'Completed',
    parentConsentId: 'cns-208',
    parentStatus: 'APPROVED',
    advisorStatus: 'APPROVED',
    wardenStatus: 'APPROVED',
    hodStatus: 'APPROVED',
    isException: false,
    createdAt: new Date('2026-06-15T10:00:00').toISOString(),
    updatedAt: new Date('2026-06-15T10:00:00').toISOString()
  }
];

export const MOCK_PASSES: DigitalPass[] = [
  {
    id: 'pass-801',
    passNumber: 'PASS-9921-X',
    requestId: 'req-101',
    studentId: 'usr-student-101',
    studentName: 'Rahul Sharma',
    registerNumber: '7376221CS108',
    department: 'Computer Science & Engineering',
    type: 'LEAVE',
    reason: 'Family function in Coimbatore city',
    destination: 'Coimbatore Town (Home)',
    validFrom: `${todayStr}T10:00`,
    validUntil: `${todayStr}T20:00`,
    status: 'ACTIVE',
    issuedBy: 'Prof. M. Ramesh (Warden) & Dr. S. Priya (HOD)',
    qrPayload: 'BITPASS:req-101:usr-student-101:20260810-ACTIVE-9921X',
    otpCode: '4829',
    createdAt: new Date(Date.now() - 3600 * 1000 * 2).toISOString()
  }
];

export const MOCK_PARENT_CONSENTS: ParentConsent[] = [
  {
    id: 'cns-101',
    requestId: 'req-101',
    studentId: 'usr-student-101',
    parentEmail: 'parent@gmail.com',
    parentPhone: '+91 98123 45678',
    token: 'parent-token-9921-abc',
    status: 'APPROVED',
    remarks: 'Approved by father for family function.',
    respondedAt: new Date(Date.now() - 3600 * 1000 * 3.5).toISOString(),
    createdAt: new Date(Date.now() - 3600 * 1000 * 4).toISOString()
  },
  {
    id: 'cns-102',
    requestId: 'req-102',
    studentId: 'usr-student-101',
    parentEmail: 'parent@gmail.com',
    parentPhone: '+91 98123 45678',
    token: 'parent-token-9922-xyz',
    status: 'PENDING',
    createdAt: new Date(Date.now() - 3600 * 1000 * 1).toISOString()
  }
];

export const MOCK_GATE_LOGS: GateLog[] = [
  {
    id: 'gate-301',
    passId: 'pass-800',
    requestId: 'req-104',
    studentId: 'usr-student-103',
    studentName: 'Karthik Raja',
    registerNumber: '7376221EC054',
    department: 'Electronics & Communication',
    gateName: 'Main Gate 1',
    securityId: 'usr-security-601',
    securityName: 'Inspector R. Selvam',
    eventType: 'EXIT',
    timestamp: new Date(Date.now() - 3600 * 1000 * 8).toISOString(),
    verificationStatus: 'SUCCESS',
    notes: 'Pass verified via QR scan.'
  },
  {
    id: 'gate-302',
    passId: 'pass-800',
    requestId: 'req-104',
    studentId: 'usr-student-103',
    studentName: 'Karthik Raja',
    registerNumber: '7376221EC054',
    department: 'Electronics & Communication',
    gateName: 'Main Gate 1',
    securityId: 'usr-security-601',
    securityName: 'Inspector R. Selvam',
    eventType: 'ENTRY',
    timestamp: new Date(Date.now() - 3600 * 1000 * 2).toISOString(),
    verificationStatus: 'SUCCESS',
    notes: 'Student re-entered campus safely.'
  }
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'adt-901',
    timestamp: new Date(Date.now() - 3600 * 1000 * 4).toISOString(),
    actorId: 'usr-student-101',
    actorName: 'Rahul Sharma',
    actorRole: 'STUDENT',
    action: 'REQUEST_CREATED',
    entityType: 'LEAVE_REQUEST',
    entityId: 'req-101',
    newState: 'SUBMITTED',
    metadata: { reason: 'Family function in Coimbatore city', destination: 'Coimbatore Town' }
  },
  {
    id: 'adt-902',
    timestamp: new Date(Date.now() - 3600 * 1000 * 3.5).toISOString(),
    actorId: 'usr-parent-201',
    actorName: 'Suresh Sharma',
    actorRole: 'PARENT',
    action: 'PARENT_APPROVED',
    entityType: 'PARENT_CONSENT',
    entityId: 'cns-101',
    previousState: 'PENDING',
    newState: 'APPROVED',
    metadata: { method: 'Tokenized Secure Portal' }
  },
  {
    id: 'adt-903',
    timestamp: new Date(Date.now() - 3600 * 1000 * 2.5).toISOString(),
    actorId: 'usr-warden-401',
    actorName: 'Prof. M. Ramesh',
    actorRole: 'WARDEN',
    action: 'WARDEN_APPROVED',
    entityType: 'LEAVE_REQUEST',
    entityId: 'req-101',
    newState: 'APPROVED',
    metadata: { hostelBlock: 'Emerald Block - A' }
  },
  {
    id: 'adt-904',
    timestamp: new Date(Date.now() - 3600 * 1000 * 2).toISOString(),
    actorId: 'usr-hod-501',
    actorName: 'Dr. S. Priya',
    actorRole: 'HOD',
    action: 'PASS_ISSUED',
    entityType: 'DIGITAL_PASS',
    entityId: 'pass-801',
    newState: 'ACTIVE',
    metadata: { passNumber: 'PASS-9921-X', validHours: 10 }
  }
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'ntf-01',
    userId: 'usr-student-101',
    title: 'Digital Pass Ready!',
    message: 'Your leave request OUT-2026-0892 has been fully approved. Pass PASS-9921-X is ready.',
    type: 'SUCCESS',
    read: false,
    linkRequestId: 'req-101',
    deliveryChannel: 'IN_APP',
    deliveryStatus: 'DELIVERED',
    createdAt: new Date(Date.now() - 3600 * 1000 * 2).toISOString()
  },
  {
    id: 'ntf-02',
    userId: 'usr-parent-201',
    title: 'New Leave Consent Needed',
    message: 'Rahul Sharma submitted an OD request for Smart India Hackathon. Please review.',
    type: 'ACTION_REQUIRED',
    read: false,
    linkRequestId: 'req-102',
    deliveryChannel: 'SMS',
    deliveryStatus: 'DEVELOPMENT_SIMULATED',
    createdAt: new Date(Date.now() - 3600 * 1000 * 1).toISOString()
  },
  {
    id: 'ntf-03',
    userId: 'usr-hod-501',
    title: 'Urgent Exception Request',
    message: 'Priya Sundaram requested an Exception Exit for Medical Emergency.',
    type: 'WARNING',
    read: false,
    linkRequestId: 'req-103',
    deliveryChannel: 'IN_APP',
    deliveryStatus: 'DELIVERED',
    createdAt: new Date(Date.now() - 1800 * 1000).toISOString()
  }
];
